### ISSUE TITLE
Tracker: CallDorado

### ISSUE THREAD

**Issue by IzzySoft** [Exodus-Privacy/etip#54]
[CallDorado](https://www.appbrain.com/stats/libraries/details/calldorado/calldorado) is a pretty invasive tracker found in several apps advertising their CallerID features (example: [`id.caller.email`](https://play.google.com/store/apps/details?id=id.caller.email). A short [summary here](https://android.izzysoft.de/help?topic=modwarnings#calldorado), quote:

> *CallDorado* supplies CallerID and injects ads there. Mediator for Admob, Facebook, Smaato, inMobi, MoPub, Flurry … According to their „[privacy policy](http://legal.calldorado.com/privacy-policy/), collect e.g. IP, DeviceID, IMEI, MAC, CallNumbers (in/out) w/ call statistics, location, contact lists, user interactions with ads. Data is shared with „sub-suppliers“ (i.e. the other networks mediated for), and possible other „third parties“ not specified in detail. User implicitly agrees by „using the Services“.

List of used permissions: INTERNET ACCESS_NETWORK_STATE ACCESS_WIFI_STATE READ_PHONE_STATE ACCESS_COARSE_LOCATION ACCESS_FINE_LOCATION WRITE_EXTERNAL_STORAGE RECEIVE_BOOT_COMPLETED READ_CONTACTS WRITE_CONTACTS PROCESS_OUTGOING_CALLS SYSTEM_ALERT_WINDOW

I have no technical details on it, but as a starting point, above mentioned app [was processed by Exodus](https://reports.exodus-privacy.eu.org/en/reports/100769/), so the Smali should be accessible for you. Package name is most likely something along `com.calldorado.android`, going by the examples [provided here](https://github.com/Calldorado-com/calldorado-template-examples).

Some marketing-buzz [can be found here](https://calldorado.com/en/). Looks like access to the real technical data is only available after signing their EULA, so I unfortunately cannot provide that.

Would be great if that tracker could be added to Exodus Privacy. Thanks in advance!

**Comment by jfoucry** [comment]
I checked during the night, we have 17368 apk containing this string (`com.calldorado.android`).
I this it's a great candidate for the next trackers add in εxodus.

**Comment by IzzySoft** [comment]
@simpnu @jfoucry thanks! Yes, it's not that wide-spread because even devs fear its intrusiveness (just check the CallDorado FAQ; I vaguely remember shaking my head in circles when I read it about a year ago or so – asked whether folks wouldn't avoid an app because of this, they answered "don't worry, everybody wants CallerID stuff"). But even not being wide-spread: when present, it's a heavy privacy violation.

As for directly contributing: I've got your invitation. I just lack the time. Already have fat too many "running projects" (being one of the F-Droid maintainers, running my own repo plus my Android site and my eBook catalog). Sorry for that.

However: feel free to parse [my repo's library definitions](https://gitlab.com/IzzyOnDroid/repo/tree/master/libs) for good candidates (just grep for `"Tracking"` in the `libinfo.txt`, matching definitions are in `libsmali.txt`). That's the ones I encountered in APKs I had downloaded, or that are still present in my repo.

**Comment by simpnu** [comment]
No need to apologize :)

Thanks for the links! I'll try to take a look at these definitions in the coming days and see what I can do from that :)

**Comment by IzzySoft** [comment]
@simpnu very much appreciated!

**Comment by simpnu** [comment]
Just to heads-up as the analysis is in progress :)

For the record, what I'm doing:

* [ ] unchecked # [checkbox:unchecked]
* [x] checked   # [checkbox:checked]
* [x] checked   # [checkbox:checked]

**Comment by simpnu** [comment]
Just a heads-up as the analysis is in progress :)

For the record, what I'm doing:

* [x] Take definitions from `libinfo.txt` and grep for `"Tracking"`
* [x] Remove definitions already in exodus using exodus API
* [ ] Check the number of apks from exodus matching these definitions
* [ ] Create a profile in ETIP for each new tracker with an interesting number of matches
* [ ] Ask for a second verification for these trackers
* [ ] Add them to exodus

**Comment by IzzySoft** [comment]
Sounds great! BTW, if you wonder about that field: it reflects F-Droid AntiFeatures. The usual suspects are Tracking and Ads. The others are rather not of interest for Exodus (e.g. NonFreeNet, NonFreeDep etc).

**Comment by simpnu** [comment]
Alright, we have added 26 new trackers, around 15 coming from your data (including CallDorado: https://reports.exodus-privacy.eu.org/en/trackers/252/) :)

Cheers!

**Comment by IzzySoft** [comment]
Yay, thanks!
